language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install postgresql-server-dev-9.5 postgresql-common
# -dev-all possible
services:
  - postgresql
install: make && sudo make install
script: make test
compiler:
  - clang
  - gcc
addons:
  postgresql: "9.5"
